#!/bin/sh

# Regex for conventional commits
# <type>(<scope>): <description>
# types: build, chore, ci, docs, feat, fix, perf, refactor, revert, style, test
pattern="^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-z0-9-]+\))?!?: .+$"

commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")

if ! echo "$commit_msg" | grep -iqE "$pattern"; then
    echo "Error: Commit message does not follow Conventional Commits format."
    echo "Format: <type>(<scope>): <description>"
    echo "Example: feat(auth): add login functionality"
    echo "Valid types: build, chore, ci, docs, feat, fix, perf, refactor, revert, style, test"
    exit 1
fi

